In [14]:
import numpy as np
x = np.array(12)
print(x)
print(x.ndim) #ndim returns the number of demensions within an array(in this case zero) also known as Rank 0 tensor

12
0


In [15]:
x = np.array([12, 3, 6, 14, 7])
print(x)
print(x.ndim) # Rank 1 tensor

[12  3  6 14  7]
1


In [18]:
# Rank 2 Tensor
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 2, 35, 1],
              [7, 80, 4, 36, 2]])
print(x)
print(x.ndim)

[[ 5 78  2 34  0]
 [ 6 79  2 35  1]
 [ 7 80  4 36  2]]
2


In [20]:
# Rank 3 Tensor
x = np.array([[[5, 78, 2, 34, 0],
              [6, 79, 2, 35, 1],
              [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
              [6, 79, 2, 35, 1],
              [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
              [6, 79, 2, 35, 1],
              [7, 80, 4, 36, 2]]])
print(x.ndim)

3


**Tensors consist of three key attributes**
*   Number of axis - also known as ndim
*   Shape which the matrix consists of: Ex([3,5])
*   Data Type - the type of data that the tensor is contained with

In [22]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images.ndim

# Rank 3 tensor

3