In [4]:
# "Relu" stands for rectified linear unit
# Example of element wise operation

# The main purpose of the element wise function is to apply a function to each element within the array independently to avoid slow loops
def naive_relu(x):
  assert len(x.shape) == 2
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = max(x[i, j], 0)

In [8]:
# Example of addition
def naive_add(x, y):
  assert len(x.shape) == 2
  assert x.shape == y.shape
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x

Numpy has well built in functions in order to do the "heavy" lifting known as BLAS are low-level and highly parallel tensor manipulation routines implemented in Fortran and C

In [6]:
import numpy as np
import time

x = np.random.random((20, 100))
y = np.random.random((20, 100))
t0 = time.time()
for _ in range(1000):
  z = x + y
  z = np.maximum(z, 0.)
print("Took: {0:.2f} s".format(time.time() - t0))


Took: 0.01 s


**VS**

In [9]:
t0 = time.time()
for _ in range(1000):
  z = naive_add(x,y)
  z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

[[1.68925802 1.08815515 1.34962386 ... 1.14303    0.8794013  0.9463685 ]
 [0.74147197 0.84605936 1.45248738 ... 1.2438318  0.70549859 0.62899732]
 [1.5992696  1.07652336 0.79551863 ... 0.88794793 0.43855731 1.21758675]
 ...
 [0.43830333 0.76064207 1.95248343 ... 1.06119705 0.71336653 0.98958043]
 [0.49652309 1.24206249 1.71054903 ... 0.46345724 1.70451196 1.1049739 ]
 [1.15502596 0.85615906 1.31764925 ... 0.83002119 1.64056909 0.40300908]]
[[1.68925802 1.08815515 1.34962386 ... 1.14303    0.8794013  0.9463685 ]
 [0.74147197 0.84605936 1.45248738 ... 1.2438318  0.70549859 0.62899732]
 [1.5992696  1.07652336 0.79551863 ... 0.88794793 0.43855731 1.21758675]
 ...
 [0.43830333 0.76064207 1.95248343 ... 1.06119705 0.71336653 0.98958043]
 [0.49652309 1.24206249 1.71054903 ... 0.46345724 1.70451196 1.1049739 ]
 [1.15502596 0.85615906 1.31764925 ... 0.83002119 1.64056909 0.40300908]]
[[1.68925802 1.08815515 1.34962386 ... 1.14303    0.8794013  0.9463685 ]
 [0.74147197 0.84605936 1.45248738 ... 